"""Render the image that goes out with a post.

The decision behind this file: **the words on the card are drafted, checked and approved
like every other word this service publishes.** They are not sliced out of the body by a
heuristic at render time. A picture carrying a sentence is making the same claim a
paragraph would, and routing it around the claim checker would put the one piece of copy
nobody reviewed on the most visible surface.

So `card_line` is a field on the draft. The model writes it, the checker reads it, the
reviewer sees it on Telegram, and the approval covers it. Rendering is then a pure
function of an approved version — which also means the image never has to be stored: it
can be regenerated byte-identically whenever it is needed.

Two practical notes.

**The font is bundled, not installed.** `python:3.11-slim` ships no fonts at all, so
relying on the system would mean the card renders in whatever the base image happens to
have — or fails. Inter's variable font is one file for every weight, and it is the
website's typeface, so the card and the site are set in the same face.

**Nothing is generated.** No image model is involved. Text in generated images is
unreliable in exactly the place it matters most — the product name — and an invented
dashboard full of invented numbers is precisely what the claim file exists to prevent.
The card is drawn, so what it says is what was approved.
"""
import logging
import textwrap
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

logger = logging.getLogger("astra.mkt.cards")

_ASSETS = Path(__file__).resolve().parent.parent / "assets"
_FONT = _ASSETS / "fonts" / "Inter.ttf"
_LOGO = _ASSETS / "logo-dark.png"

#: 1.91:1 — LinkedIn's own ratio. Anything else is letterboxed or cropped by the feed, and
#: a cropped card loses the line it exists to carry.
SIZE = (1200, 627)

# The website's palette, so a card and the site are recognisably the same brand.
INK = (11, 17, 32)            # ink-900
INK_SOFT = (30, 41, 59)       # ink-700
BRAND = (178, 70, 212)        # brand-500
BRAND_DIM = (105, 33, 123)    # brand-800
WHITE = (255, 255, 255)
MUTED = (148, 163, 184)

_MARGIN = 80
#: Below this the line is set larger. A short, sharp line deserves the space; a long one
#: needs the room more than it needs the drama.
_SHORT_LINE = 60


class CardError(Exception):
    """The card could not be drawn. Never raised for an empty line — see `render`."""


def _font(size: int, weight: str = "Regular") -> ImageFont.FreeTypeFont:
    if not _FONT.exists():
        # Pillow's own error here is "cannot open resource", which sends whoever reads it
        # looking at Pillow. The actual cause is always the same: the asset did not make
        # it into the image. Say that instead.
        raise CardError(
            f"The Inter font is missing from the deployed image ({_FONT}). It is bundled "
            "on purpose — python:3.11-slim ships no fonts — so check .dockerignore and "
            "that app/assets/ is committed."
        )
    font = ImageFont.truetype(str(_FONT), size)
    try:
        font.set_variation_by_name(weight)
    except Exception:  # noqa: BLE001 — a build without variable-font support
        # Not fatal: the card renders in Regular rather than not at all. Logged once so a
        # sudden loss of weight contrast has an explanation somewhere.
        logger.warning("this Pillow build cannot set the %s axis; using Regular", weight)
    return font


def _wrap(draw: ImageDraw.ImageDraw, text: str, font, max_width: int) -> list[str]:
    """Wrap to a pixel width, not a character count.

    `textwrap` alone counts characters, and Inter is proportional — "MMMM" and "iiii" are
    the same four characters and nowhere near the same width, so a character-based wrap
    overflows on some lines and wastes half the card on others.
    """
    words = text.split()
    lines: list[str] = []
    current: list[str] = []

    for word in words:
        candidate = " ".join([*current, word])
        if draw.textlength(candidate, font=font) <= max_width or not current:
            current.append(word)
        else:
            lines.append(" ".join(current))
            current = [word]
    if current:
        lines.append(" ".join(current))
    return lines


def _backdrop() -> Image.Image:
    """Ink ground with a brand glow in the lower right.

    Drawn at quarter scale and scaled up: a radial blend is dozens of overlapping ellipses,
    and at full size that is slow enough to notice on a request. Upscaling a soft gradient
    costs nothing visually because there is no detail in it to lose.
    """
    small = Image.new("RGB", (SIZE[0] // 4, SIZE[1] // 4), INK)
    draw = ImageDraw.Draw(small)

    cx, cy = int(small.width * 0.86), int(small.height * 0.92)
    steps = 44
    for i in range(steps, 0, -1):
        t = i / steps
        radius = int(small.width * 0.75 * t)
        # Ease the blend so the glow falls off like light rather than like a cone.
        mix = (1 - t) ** 2
        colour = tuple(
            int(INK[c] + (BRAND_DIM[c] - INK[c]) * mix) for c in range(3)
        )
        draw.ellipse([cx - radius, cy - radius, cx + radius, cy + radius], fill=colour)

    # Blur before upscaling. Forty-four discrete ellipses leave visible concentric rings —
    # the eye finds edges in a gradient far more readily than in detail — and a blur at
    # quarter scale erases them for almost nothing. Doing it after the resize would cost
    # sixteen times as many pixels for the same result.
    small = small.filter(ImageFilter.GaussianBlur(radius=6))
    return small.resize(SIZE, Image.LANCZOS)


def render(line: str, *, eyebrow: str | None = None,
           footer: str = "technomateai.com") -> bytes:
    """Draw one card. Returns PNG bytes.

    `line` is the approved `card_line`. An empty one is a caller error rather than a blank
    card: a card with no message is worse than no card, because it still occupies the post.
    """
    if not line or not line.strip():
        raise CardError("A card needs a line; refusing to render an empty one.")

    image = _backdrop()
    draw = ImageDraw.Draw(image)
    text_width = SIZE[0] - (_MARGIN * 2)

    # ── Logo, top left ────────────────────────────────────────────────────────
    top = _MARGIN
    if _LOGO.exists():
        logo = Image.open(_LOGO).convert("RGBA")
        height = 66
        logo = logo.resize(
            (int(logo.width * height / logo.height), height), Image.LANCZOS
        )
        image.paste(logo, (_MARGIN, top), logo)
        top += height + 48
    else:
        logger.warning("logo asset missing at %s; card rendered without it", _LOGO)

    # ── Eyebrow ───────────────────────────────────────────────────────────────
    if eyebrow:
        eyebrow_font = _font(22, "SemiBold")
        # Letter-spaced by hand: Pillow has no tracking, and uppercase set solid reads as
        # a shout rather than a label.
        spaced = " ".join(eyebrow.upper())
        draw.text((_MARGIN, top), spaced, font=eyebrow_font, fill=BRAND)
        top += 46

    # ── The line ──────────────────────────────────────────────────────────────
    size = 68 if len(line) <= _SHORT_LINE else 52
    for _attempt in range(6):
        line_font = _font(size, "Bold")
        lines = _wrap(draw, line.strip(), line_font, text_width)
        spacing = int(size * 1.28)
        needed = len(lines) * spacing
        if top + needed <= SIZE[1] - _MARGIN - 60:
            break
        # Too tall for the card. Shrink rather than crop — a truncated sentence on a
        # graphic is the kind of mistake that gets screenshotted.
        size = int(size * 0.86)
    else:
        logger.warning("card line did not fit after 6 reductions: %r", line[:60])

    y = top
    for text_line in lines:
        draw.text((_MARGIN, y), text_line, font=line_font, fill=WHITE)
        y += spacing

    # ── Footer ────────────────────────────────────────────────────────────────
    rule_y = SIZE[1] - _MARGIN - 34
    draw.line([(_MARGIN, rule_y), (_MARGIN + 68, rule_y)], fill=BRAND, width=4)
    draw.text((_MARGIN + 88, rule_y - 13), footer, font=_font(24, "SemiBold"), fill=MUTED)

    buffer = BytesIO()
    # optimize because this is served on every request and uploaded to LinkedIn; the few
    # milliseconds buy a materially smaller file.
    image.save(buffer, format="PNG", optimize=True)
    return buffer.getvalue()


def fallback_line(body: str) -> str:
    """The opening line of the post, for versions written before `card_line` existed.

    Deliberately dumb, and deliberately not a model call: this is a compatibility shim for
    old rows, not a second way of authoring card copy. New drafts always carry their own
    approved line.
    """
    first = next((p.strip() for p in body.split("\n") if p.strip()), "")
    sentence = first.split(". ")[0].strip().rstrip(".")
    return textwrap.shorten(sentence, width=110, placeholder="…") if sentence else ""
